# Generated by Django 6.0.2 on 2026-03-02 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=50)),
                ('promotion', models.IntegerField(help_text='Année de la promotion (ex: 2026)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type_projet', models.CharField(choices=[('PFE', "Projet de Fin d'Études"), ('PFA', "Projet de Fin d'Année"), ('MINI', 'Mini Projet'), ('STAGE', 'Stage')], default='PFE', max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='EN_ATTENTE', max_length=15)),
                ('technologies', models.CharField(help_text='Technologies utilisées, séparées par des virgules (ex: React, Django, PostgreSQL)', max_length=500)),
                ('annee_universitaire', models.CharField(help_text='Format: 2025-2026', max_length=9)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='projets/documents/')),
                ('lien_github', models.URLField(blank=True, null=True)),
                ('lien_demo', models.URLField(blank=True, null=True)),
                ('etudiants', models.ManyToManyField(blank=True, related_name='projets', to='api.etudiant')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_tutores', to='api.enseignant')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
