# Generated by Django 6.0.2 on 2026-03-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('entreprise', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('type_stage', models.CharField(choices=[('OBSERVATION', "Stage d'observation"), ('TECHNICIEN', 'Stage technicien'), ('INGENIEUR', 'Stage ingénieur'), ('PFE', 'Stage PFE')], default='PFE', max_length=15)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='EN_COURS', max_length=15)),
                ('technologies', models.CharField(help_text='Technologies utilisées, séparées par des virgules', max_length=500)),
                ('annee_universitaire', models.CharField(help_text='Format: 2025-2026', max_length=9)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stages/images/')),
                ('rapport', models.FileField(blank=True, null=True, upload_to='stages/rapports/')),
                ('lien_entreprise', models.URLField(blank=True, null=True)),
                ('maitre_stage', models.CharField(blank=True, help_text='Nom du maître de stage en entreprise', max_length=200)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.etudiant')),
                ('tuteur_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_tutores', to='api.enseignant')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'ordering': ['-date_creation'],
            },
        ),
    ]
