# Generated by Django 6.0.2 on 2026-03-13 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_groupeprojet_projet_groupe_stage_niveau_academique_duree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeprojet',
            name='code',
            field=models.CharField(choices=[('SI', 'Systèmes D_Information'), ('RS', 'Réseaux et Systèmes'), ('ADMIN_RESEAUX', 'Administration Réseaux'), ('SUPERVISION', 'Supervision'), ('SECURITE', 'Sécurité'), ('AUTRES', 'Autres')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Raison sociale de l'entreprise", max_length=200)),
                ('secteur', models.CharField(blank=True, help_text="Secteur d'activité", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('ville', models.CharField(blank=True, default='Bobo-Dioulasso', max_length=100)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('est_valide', models.BooleanField(default=False, help_text='Compte validé par un administrateur avant publication des offres')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type_stage', models.CharField(choices=[('OBSERVATION', "Stage d'observation"), ('TECHNICIEN', 'Stage technicien'), ('INGENIEUR', 'Stage ingénieur'), ('PFE', 'Stage PFE')], default='PFE', max_length=15)),
                ('niveau_academique', models.CharField(blank=True, choices=[('LICENCE', 'Licence'), ('IT', 'IT (Ingénieur des Travaux)'), ('MASTER', 'Master'), ('IC', 'IC (Ingénieur Concepteur)')], max_length=10)),
                ('duree', models.PositiveSmallIntegerField(blank=True, help_text='Durée du stage en semaines', null=True)),
                ('technologies', models.CharField(blank=True, help_text='Technologies requises, séparées par des virgules', max_length=500)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_limite_candidature', models.DateField(blank=True, null=True)),
                ('remuneration', models.CharField(blank=True, help_text='Rémunération mensuelle (ex: 50 000 FCFA)', max_length=100)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('FERME', 'Fermé'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='api.entreprise')),
            ],
            options={
                'verbose_name': 'Offre de Stage',
                'verbose_name_plural': 'Offres de Stage',
                'ordering': ['-date_creation'],
            },
        ),
    ]
