# Generated by Django 6.0.3 on 2026-03-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entreprise_offrestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='CV Étudiant', max_length=200)),
                ('resume', models.TextField(blank=True)),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('disponible_pour_stage', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('competences', models.ManyToManyField(blank=True, related_name='cvs', to='api.competence')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='api.etudiant')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
                'ordering': ['-date_modification'],
            },
        ),
    ]
