# Generated by Django 6.0.3 on 2026-03-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_competence_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('email_institutionnel', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Étudiant Autorisé',
                'verbose_name_plural': 'Étudiants Autorisés',
                'ordering': ['matricule'],
            },
        ),
    ]
